name: MacOS CI Test
on:
  push:
    branches: [main, master, dev]
  pull_request:
    branches: [main, master, dev]
permissions:
  contents: read
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f086349bfa2bd1361f7909c78558e816508cdc10 # v2.8.0
        with:
          egress-policy: audit
          disable-telemetry: true
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - name: Setup Cpp
        uses: aminya/setup-cpp@290824452986e378826155f3379d31bce8753d76 # v0.37.0
        with:
          clangtidy: true
      - name: configure
        run: |
          cmake -H. -Bbuild -G "Unix Makefiles" -DCMAKE_BUILD_TYPE="Debug"
      - name: building
        run: |
          cmake --build build --config Debug --target ComponentsTests QueriesTests SystemsTests Vector2DTests
      - name: run component unit tests
        working-directory: ./build/bin
        run: |
          ./ComponentsTests
      - name: run queries unit tests
        working-directory: ./build/bin
        run: |
          ./QueriesTests
      - name: run systems unit tests
        working-directory: ./build/bin
        run: |
          ./SystemsTests
      - name: run systems vector2d tests
        working-directory: ./build/bin
        run: |
          ./Vector2DTests
